#MySql基础配置
spring:
     datasource:
         url: jdbc:mysql://127.0.0.1:3306/coldchain?serverTimezone=GMT%2B8
         username: root
         password: root
#         driver-class-name: com.mysql.cj.jdbc.Driver
# 禁用模板缓存
     thymeleaf:
       cache: false
#开启热加载
spring.devtools.restart.enabled: true
#设置重启的目录
spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
spring.devtools.restart.exclude: templates/**
#sql打印日志
logging.level.com.coldchain.demo.mapper: debug

mybatis-plus:
  global-config:
      db-column-underline: true

